# Generated by Django 5.0.3 on 2024-03-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYCUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycusers',
            name='email_before_update',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kycusers',
            name='phone_number_before_update',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
