# Generated by Django 5.0.3 on 2024-03-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYCUser', '0002_kycusers_email_before_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycusers',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
